### ISSUE TITLE
Third Web Dev module error

### ISSUE THREAD

**Issue by lovelace02** [evilgon/EVM-Lottory-Dapp#1]
I forked your repo and run it in my local.
But doesn't work very well.
I think it is because third web dev module.
Could you explain about it?

**Comment by evilgon** [comment]
Yes, of course.
Third web dev module is new web3 module for solidity dapp.
You may want to build a smart contract from the ground up, or deploy a prebuilt solution that meets your needs.
You can read it on https://thirdweb.com/
Regards.
